---
- name: Update apt package cache
  tags: etckeeper
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install etckeeper VCS package
  tags: etckeeper
  with_flattened:
    - etckeeper_vcs
    - etckeeper_package_list
  apt:
    state=installed
    name={{ item }}
