---
- name: Assert platform is supported
  tags: etckeeper
  assert:
    that:
      - ansible_os_family in ['Debian']

- name: Assert etckeeper_vcs is valid
  tags: etckeeper
  assert:
    that:
      - etckeeper_vcs in ['git', 'mercurial', 'bzr', 'darcs']


- include_vars: "{{ ansible_os_family }}.yml"
  tags: etckeeper


# Install the configuration first.
#   This ensures initialization of etckeeper uses the configured values.
- name: Install etckeeper configuration directory
  tags: etckeeper
  file:
    state=directory
    mode=0755
    owner=root
    group=root
    dest=/etc/etckeeper

- name: Install etckeeper configuration
  tags: etckeeper
  template:
    src=etckeeper.j2
    dest=/etc/etckeeper/etckeeper.conf
    mode=0644
    owner=root
    group=root


- include: Debian.yml
  when: ansible_os_family == 'Debian'
