---
- name: Install EPEL repository configuration
  tags: etckeeper
  template:
    src=epel.repo.j2
    dest=/etc/yum.repos.d/epel.repo
    owner=0
    group=0
    mode=0644

- name: Update yum package cache
  tags: etckeeper
  command: yum --assumeyes --quiet makecache


- name: Install etckeeper VCS package RedHat
  tags: etckeeper
  with_flattened:
    - etckeeper_vcs
    - etckeeper_package_list
  yum:
    state=installed
    name={{ item }}

- name: Initialise etckeeper
  tags: etckeeper
  command: etckeeper init
    creates=/etc/.etckeeper
